#!/usr/bin/env bash

[[ $- == *i* ]] || return 0

set -o vi

shopt -s checkwinsize
shopt -s histappend

complete -c man which
complete -cf doas

export HISTCONTROL="erasedups:ignorespace"

. "${HOME}/.config/shells/common/paths.sh"

FZF_ALT_C_COMMAND=
eval "$(fzf --bash)"
