#!/bin/sh

common_dir="${XDG_CONFIG_HOME:-${HOME}/.config}/shells/common"

if [ -d "${common_dir}" ]; then
	for f in "${common_dir}"/*.sh ; do
		[ -r "$f" ] && . "$f"
	done
	unset f
fi

unset common_dir
